In [9]:
import numpy as np
def has_a_winner(board):
    
    # 檢查行
    board_size=15
    move=np.argmax(board)
    player= 1 if np.max(board)%2==0 else -1
    print(np.max(board)%2==0)
    print("player",player)
    row=move//board_size
    col=move%board_size
    print(row,col,board[row][col])
    
    p1=(board+1)%2
    all=np.where(board<0,0,1)
    p2=all-p1
    board=p1-p2
    print(board)
    status=[False for i in range(4)]

    for c in range(board_size - 5):
        if board[row][c] == board[row][c+1] == board[row][c+2] == board[row][c+3] ==  board[row][c+4] == board[row][c+5] == player:
            status[0] = True 

    # 檢查列
    for r in range(board_size - 5):
        if board[r][col] == board[r+1][col] == board[r+2][col] == board[r+3][col] == board[r+4][col] ==  board[r+5][col] == player:
            status[1] = True 

    # 檢查正對角線
    for i in range(board_size - 5):
        if row - i >= 0 and col - i >= 0 and row - i + 5 < board_size and col - i + 5 < board_size:
            if board[row-i][col-i] == board[row-i+1][col-i+1] == board[row-i+2][col-i+2] == board[row-i+3][col-i+3] == board[row-i+4][col-i+4] == board[row-i+5][col-i+5] == player:
                status[2] = True 

    # 檢查負對角線
    for i in range(board_size - 5):
        if row + i < board_size and col - i >= 0 and row + i - 5 >= 0 and col - i + 5 < board_size:
            if board[row+i][col-i] == board[row+i-1][col-i+1] == board[row+i-2][col-i+2] == board[row+i-3][col-i+3] == board[row+i-4][col-i+4] == board[row+i-5][col-i+5] == player:
                status[3] = True 
# ---------------------------------------------------------------------------------------------------            
    # 檢查行        
    for c in range(board_size - 4):
        if board[row][c] == board[row][c+1] == board[row][c+2] == board[row][c+3] == board[row][c+4] == player and not status[0]:
            return True,player

    # 檢查列
    for r in range(board_size - 4):
        if board[r][col] == board[r+1][col] == board[r+2][col] == board[r+3][col] == board[r+4][col] == player and not status[1]:
            return True,player

    # 檢查正對角線
    for i in range(board_size - 4):
        if row - i >= 0 and col - i >= 0 and row - i + 4 < board_size and col - i + 4 < board_size:
            if board[row-i][col-i] == board[row-i+1][col-i+1] == board[row-i+2][col-i+2] == board[row-i+3][col-i+3] == board[row-i+4][col-i+4] == player and not status[2]:
                return True,player
            
    for i in range(board_size - 4):
        if row + i < board_size and col - i >= 0 and row + i - 5 >= 0 and col - i + 5 < board_size:
            if board[row+i][col-i] == board[row+i-1][col-i+1] == board[row+i-2][col-i+2] == board[row+i-3][col-i+3] == board[row+i-4][col-i+4] == player and not status[3]:
                return True,player

    return False,-1


a=[-1 for i in range(15)]
print(a)
states=np.array(
    [[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [-1, -1, -1, -1, -1, 28, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [-1, -1, -1, -1, 26, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [-1, -1, -1, 24, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [-1, -1, 22, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [10, 20, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [30, 12, 14, 16, 8, 18, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [6, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [4, 5, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [2, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
     [0, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

print(has_a_winner(states))

[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
True
player 1
10 0 30
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  0  0  0  0  0  0  0  0  0]
 [ 1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0]]
(False, -1)
